export enum ContentNodeType {
  A = "a",
  ADDRESS = "address",
  BR = "br",
  BUTTON = "button",
  BUTTON_CONFIRM = "buttonConfirm",
  BUTTON_LINK = "buttonLink",
  CALLOUT = "callout",
  CARD = "card",
  COLLAPSIBLE_PANEL = "collapsiblePanel",
  COMPONENT = "component",
  CONDITIONAL = "conditional",
  COUNTDOWN_TIMER = "countdownTimer",
  FILE_UPLOAD = "fileUpload",
  FOR_EACH = "forEach",
  H1 = "h1",
  H2 = "h2",
  H3 = "h3",
  H4 = "h4",
  H5 = "h5",
  H6 = "h6",
  HR = "hr",
  ILLUSTRATION = "illustration",
  IMG = "img",
  INPUT = "input",
  INPUT_CHECKBOX_BUTTON = "inputCheckboxButton",
  JSON_ARRAY = "jsonArray",
  LABEL = "label",
  MULTI_SELECT = "multiSelect",
  OL = "ol",
  P = "p",
  RADIO_SELECT = "radioSelect",
  RESOURCE_EDITOR = "resourceEditor",
  RESOURCES_LIST = "resourcesList",
  ROW = "row",
  SELECT = "select",
  SMALL = "small",
  TABLE = "table",
  TEXT = "text",
  TEXTAREA = "textarea",
  UL = "ul",
  VIDEO = "video",
}

export enum ContentNodeInputType {
  AGE = "age",
  CALENDAR = "calendar",
  CHECKBOX = "checkbox",
  CURRENCY = "currency",
  DATE = "date",
  INTEGER = "integer",
  NUMBER = "number",
  PASSWORD = "password",
  TEL = "tel",
  TEXT = "text",
}

export enum SerializedStyledComponentKeys {
  A = "A",
  Button = "Button",
  ButtonLink = "ButtonLink",
  H1 = "H1",
  H2 = "H2",
  H3 = "H3",
  H4 = "H4",
  H5 = "H5",
  H6 = "H6",
  HR = "HR",
  Input = "Input",
  P = "P",
  Select = "Select",
  Small = "Small",
  Table = "Table",
  Textarea = "Textarea",
}
